name: "Lint and Tests Pipeline"
on: 
  push: 
    branches: 
      - master 
  pull_request: 

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - name: Install dependencies
      run: |
        make requirements
    - name: Lint with Black
      run: |
        make check-black
    - name: Style check with Flake8
      run: |
        make check-flake8
