name: "Lint and Tests Pipeline"
on: 
  push: 
    branches: 
      - main 
  pull_request: 

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
    - name: Install dependencies
      run: |
        make requirements
    - name: Lint with Black
      run: |
        make check-black
    - name: Style check with Flake8
      run: |
        make check-flake8
    - name: dokcer login 
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker remove images
      run: docker build . --tag last-gas-run
    - name: docker push
      run: docker push ${{secrets.DOCKER_USER}}/last-gas:last-gas-run
